name: Despliegue a Azure
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4  # Corregido: Evita advertencias de Node 20
    
    - name: Azure Login
      uses: azure/login@v2      # Corregido: Versión moderna sin dependencias viejas
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Desplegar Bicep
      uses: azure/arm-deploy@v2  # Corregido: Versión moderna optimizada
      with:
        scope: subscription
        region: spaincentral
        template: ./main.bicep
        deploymentName: github-deploy-01
